apiVersion: v1
kind: Service
metadata:
  name: {{ include "facis-ai-insight.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "facis-ai-insight.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "facis-ai-insight.selectorLabels" . | nindent 4 }}
