<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import ToggleButton from 'primevue/togglebutton'
import DataTable from 'primevue/datatable'
import Column from 'primevue/column'
import InputText from 'primevue/inputtext'
import PageHeader from '@/components/common/PageHeader.vue'
import KpiCard from '@/components/common/KpiCard.vue'
import { getMeters, getMeterHistory, getPriceHistory, getPVSystems, getPVHistory } from '@/services/api'
import { generateRecommendations } from '@/services/analytics'
import type { Recommendation } from '@/services/analytics'

const loading   = ref(true)
const isLive    = ref(false)
const recommendations = ref<Recommendation[]>([])
const showCards  = ref(true)
const searchQuery = ref('')
const activeUseCaseFilter  = ref<string | null>(null)
const activeCategoryFilter = ref<string | null>(null)

async function fetchData(): Promise<void> {
  loading.value = true
  try {
    const [metersRes, pvRes] = await Promise.all([getMeters(), getPVSystems()])
    if (!metersRes) throw new Error('no data')

    const firstMeterId = metersRes.meters[0]?.meter_id
    const firstPvId    = pvRes?.systems[0]?.system_id

    const [mHist, priceHist, pvHist] = await Promise.all([
      firstMeterId ? getMeterHistory(firstMeterId) : Promise.resolve(null),
      getPriceHistory(),
      firstPvId ? getPVHistory(firstPvId) : Promise.resolve(null)
    ])

    if (priceHist?.prices && mHist?.readings && pvHist?.readings) {
      recommendations.value = generateRecommendations(
        priceHist.prices,
        mHist.readings,
        pvHist.readings
      )
      isLive.value = recommendations.value.length > 0
    }
  } catch {
    recommendations.value = []
  } finally {
    loading.value = false
  }
}

onMounted(() => fetchData())

const filtered = computed(() => {
  let result = [...recommendations.value]
  if (searchQuery.value) {
    const q = searchQuery.value.toLowerCase()
    result = result.filter(r => r.title.toLowerCase().includes(q) || r.explanation.toLowerCase().includes(q))
  }
  if (activeUseCaseFilter.value)  result = result.filter(r => r.useCase === activeUseCaseFilter.value)
  if (activeCategoryFilter.value) result = result.filter(r => r.category === activeCategoryFilter.value)
  return result
})

const summary = computed(() => ({
  total:  recommendations.value.length,
  high:   recommendations.value.filter(r => r.priority === 'high').length,
  medium: recommendations.value.filter(r => r.priority === 'medium').length,
  energy: recommendations.value.filter(r => r.useCase === 'Smart Energy').length,
  city:   recommendations.value.filter(r => r.useCase === 'Smart City').length
}))

function priorityColor(p: string): string {
  if (p === 'high') return '#ef4444'
  if (p === 'medium') return '#f59e0b'
  return '#94a3b8'
}

function categoryIcon(c: string): string {
  switch (c) {
    case 'cost_saving': return 'pi-euro'
    case 'efficiency':  return 'pi-chart-line'
    case 'maintenance': return 'pi-wrench'
    case 'safety':      return 'pi-shield'
    default:            return 'pi-lightbulb'
  }
}

function categoryLabel(c: string): string {
  return c.replace('_', ' ').replace(/\b\w/g, l => l.toUpperCase())
}

function useCaseColor(uc: string): string {
  if (uc === 'Smart Energy') return '#f59e0b'
  if (uc === 'Smart City')   return '#8b5cf6'
  return '#06b6d4'
}

function formatDate(ts: string): string {
  try { return new Date(ts).toLocaleString('en-GB', { day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit' }) }
  catch { return ts }
}
</script>

<template>
  <div class="view-page">
    <PageHeader
      title="Recommendations"
      subtitle="Cost and efficiency recommendations computed from live price, meter, and PV telemetry — advisory only"
      :breadcrumbs="[{ label: 'Analytics' }, { label: 'Recommendations' }]"
    >
      <template #actions>
        <ToggleButton v-model="showCards" on-label="Cards" off-label="Table" on-icon="pi pi-th-large" off-icon="pi pi-list" size="small" />
      </template>
    </PageHeader>

    <div v-if="isLive" class="live-banner">
      <span class="live-dot"></span> Computed from live price feed + meter + PV telemetry
    </div>

    <div class="view-body">
      <div class="advisory-banner">
        <i class="pi pi-shield advisory-banner__icon"></i>
        <div><strong>Advisory Only — No Automated Control.</strong> All recommendations are generated by the FACIS analytics engine from live telemetry. No action is implemented automatically. All changes require operator review and manual execution.</div>
      </div>

      <div v-if="loading" class="loading-state">
        <i class="pi pi-spin pi-spinner" style="font-size:1.5rem;color:var(--facis-primary)"></i>
        <span>Generating recommendations from live data…</span>
      </div>

      <template v-else>
        <div class="grid-kpi">
          <KpiCard label="Total Recommendations" :value="summary.total" trend="stable" icon="pi-lightbulb" color="#22c55e" />
          <KpiCard label="High Priority" :value="summary.high" trend="stable" icon="pi-flag" color="#ef4444" />
          <KpiCard label="Medium Priority" :value="summary.medium" trend="stable" icon="pi-minus" color="#f59e0b" />
          <KpiCard label="Energy" :value="summary.energy" trend="stable" icon="pi-bolt" color="#f59e0b" />
          <KpiCard label="Smart City" :value="summary.city" trend="stable" icon="pi-map" color="#8b5cf6" />
        </div>

        <div class="filter-bar">
          <div class="filter-group">
            <span class="filter-group__label">Use Case:</span>
            <button v-for="uc in ['Smart Energy', 'Smart City', 'Cross-Domain']" :key="uc" class="filter-chip" :class="{ 'filter-chip--active': activeUseCaseFilter === uc }" @click="activeUseCaseFilter = activeUseCaseFilter === uc ? null : uc">{{ uc }}</button>
          </div>
          <div class="filter-group">
            <span class="filter-group__label">Category:</span>
            <button v-for="cat in ['cost_saving', 'efficiency', 'maintenance', 'safety']" :key="cat" class="filter-chip" :class="{ 'filter-chip--active': activeCategoryFilter === cat }" @click="activeCategoryFilter = activeCategoryFilter === cat ? null : cat">{{ categoryLabel(cat) }}</button>
          </div>
          <span class="search-wrap" style="margin-left:auto">
            <i class="pi pi-search"></i>
            <InputText v-model="searchQuery" placeholder="Search…" size="small" style="padding-left:2rem;width:220px" />
          </span>
        </div>

        <div v-if="!recommendations.length" class="card card-body empty-state">
          <i class="pi pi-info-circle" style="font-size:1.5rem;color:var(--facis-text-muted)"></i>
          <div>
            <div style="font-weight:600;color:var(--facis-text)">No recommendations generated</div>
            <div style="font-size:0.8rem;color:var(--facis-text-secondary)">Ensure simulation is running and price/meter/PV data is available.</div>
          </div>
        </div>

        <div v-else-if="showCards" class="rec-cards-grid">
          <div v-for="rec in filtered" :key="rec.id" class="rec-card card">
            <div class="rec-card__header">
              <div class="rec-icon" :style="{ background: priorityColor(rec.priority) + '18', color: priorityColor(rec.priority) }">
                <i :class="`pi ${categoryIcon(rec.category)}`"></i>
              </div>
              <div class="rec-card__title-block">
                <div class="rec-card__title">{{ rec.title }}</div>
                <div class="rec-card__badges">
                  <span class="uc-badge" :style="{ background: useCaseColor(rec.useCase) + '18', color: useCaseColor(rec.useCase) }">{{ rec.useCase }}</span>
                  <span class="priority-badge" :style="{ background: priorityColor(rec.priority) + '18', color: priorityColor(rec.priority) }">{{ rec.priority }} priority</span>
                </div>
              </div>
            </div>
            <div class="rec-card__summary">{{ rec.summary }}</div>
            <p class="rec-card__explanation">{{ rec.explanation }}</p>
            <div class="rec-card__metrics">
              <div class="rec-metric"><span class="rec-metric__label">Affected Object</span><span class="rec-metric__value">{{ rec.affectedObject }}</span></div>
              <div class="rec-metric"><span class="rec-metric__label">Est. Impact</span><span class="rec-metric__value rec-metric__value--impact">{{ rec.estimatedImpact }}</span></div>
            </div>
            <div class="confidence-row">
              <span class="confidence-label">Confidence</span>
              <div class="confidence-bar-bg"><div class="confidence-bar-fill" :style="{ width: (rec.confidence * 100) + '%', background: rec.confidence >= 0.85 ? 'var(--facis-success)' : 'var(--facis-warning)' }" /></div>
              <span class="confidence-pct">{{ Math.round(rec.confidence * 100) }}%</span>
            </div>
            <div class="advisory-note"><i class="pi pi-lock advisory-note__icon"></i><span>{{ rec.advisoryNote }}</span></div>
          </div>
        </div>

        <div v-else class="card">
          <div class="table-meta"><span class="table-title">{{ filtered.length }} recommendations</span></div>
          <DataTable :value="filtered" row-hover removable-sort scrollable>
            <template #empty><div class="empty-row">No recommendations match your filters.</div></template>
            <Column field="title" header="Title" sortable />
            <Column field="useCase" header="Use Case" sortable style="width:130px">
              <template #body="{ data }"><span class="uc-badge" :style="{ background: useCaseColor(data.useCase) + '18', color: useCaseColor(data.useCase) }">{{ data.useCase }}</span></template>
            </Column>
            <Column field="priority" header="Priority" sortable style="width:100px">
              <template #body="{ data }"><span class="priority-badge" :style="{ background: priorityColor(data.priority) + '18', color: priorityColor(data.priority) }">{{ data.priority }}</span></template>
            </Column>
            <Column field="estimatedImpact" header="Est. Impact" sortable><template #body="{ data }"><span class="impact-text">{{ data.estimatedImpact }}</span></template></Column>
            <Column field="confidence" header="Confidence" sortable style="width:100px">
              <template #body="{ data }"><span class="conf-chip">{{ Math.round(data.confidence * 100) }}%</span></template>
            </Column>
            <Column field="createdAt" header="Created" sortable style="width:160px">
              <template #body="{ data }"><span class="ts">{{ formatDate(data.createdAt) }}</span></template>
            </Column>
          </DataTable>
        </div>
      </template>
    </div>
  </div>
</template>

<style scoped>
.live-banner { display: flex; align-items: center; gap: 0.5rem; font-size: 0.75rem; font-weight: 600; color: #15803d; background: #dcfce7; padding: 0.375rem 1.5rem; border-bottom: 1px solid #bbf7d0; }
.live-dot { width: 7px; height: 7px; border-radius: 50%; background: #22c55e; animation: pulse 1.5s infinite; }
@keyframes pulse { 0%, 100% { opacity: 1; } 50% { opacity: 0.4; } }
.loading-state { display: flex; align-items: center; justify-content: center; gap: 0.75rem; padding: 4rem; color: var(--facis-text-secondary); font-size: 0.875rem; }
.empty-state { display: flex; align-items: center; gap: 0.75rem; padding: 2rem; }

.view-page { display: flex; flex-direction: column; }
.view-body { padding: 1.5rem; display: flex; flex-direction: column; gap: 1.5rem; }
.advisory-banner { display: flex; align-items: flex-start; gap: 0.875rem; padding: 1rem 1.25rem; background: #fef3c7; border: 1px solid #fde68a; border-radius: var(--facis-radius); font-size: 0.875rem; color: #78350f; line-height: 1.5; }
.advisory-banner__icon { font-size: 1rem; color: #92400e; flex-shrink: 0; padding-top: 0.1rem; }
.filter-bar { display: flex; align-items: center; gap: 1rem; flex-wrap: wrap; background: var(--facis-surface); border: 1px solid var(--facis-border); border-radius: var(--facis-radius); padding: 0.75rem 1.25rem; box-shadow: var(--facis-shadow); }
.filter-group { display: flex; align-items: center; gap: 0.375rem; }
.filter-group__label { font-size: 0.75rem; font-weight: 500; color: var(--facis-text-secondary); }
.filter-chip { font-size: 0.75rem; font-weight: 500; padding: 0.2rem 0.625rem; border-radius: 20px; border: 1px solid var(--facis-border); background: var(--facis-surface); color: var(--facis-text-secondary); cursor: pointer; transition: all 0.15s; }
.filter-chip:hover { border-color: var(--facis-primary); color: var(--facis-primary); }
.filter-chip--active { background: var(--facis-primary-light); border-color: var(--facis-primary); color: var(--facis-primary); }
.search-wrap { position: relative; display: flex; align-items: center; }
.search-wrap .pi-search { position: absolute; left: 0.6rem; color: var(--facis-text-muted); font-size: 0.8rem; z-index: 1; }
.rec-cards-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(420px, 1fr)); gap: 1rem; }
@media (max-width: 900px) { .rec-cards-grid { grid-template-columns: 1fr; } }
.rec-card { display: flex; flex-direction: column; gap: 0.75rem; padding: 1.25rem; }
.rec-card__header { display: flex; align-items: flex-start; gap: 0.875rem; }
.rec-icon { width: 40px; height: 40px; border-radius: var(--facis-radius-sm); display: flex; align-items: center; justify-content: center; font-size: 1.1rem; flex-shrink: 0; }
.rec-card__title-block { flex: 1; display: flex; flex-direction: column; gap: 0.3rem; }
.rec-card__title { font-size: 0.9rem; font-weight: 600; color: var(--facis-text); }
.rec-card__badges { display: flex; align-items: center; gap: 0.4rem; flex-wrap: wrap; }
.uc-badge, .priority-badge { font-size: 0.7rem; font-weight: 700; padding: 0.15rem 0.5rem; border-radius: 20px; text-transform: capitalize; }
.rec-card__summary { font-size: 0.82rem; font-weight: 500; color: var(--facis-text); background: var(--facis-surface-2); padding: 0.5rem 0.75rem; border-radius: var(--facis-radius-sm); border-left: 3px solid var(--facis-primary); }
.rec-card__explanation { font-size: 0.82rem; color: var(--facis-text-secondary); line-height: 1.6; }
.rec-card__metrics { display: flex; gap: 1.5rem; padding: 0.75rem 0; border-top: 1px solid var(--facis-border); border-bottom: 1px solid var(--facis-border); }
.rec-metric { display: flex; flex-direction: column; gap: 0.2rem; }
.rec-metric__label { font-size: 0.72rem; font-weight: 500; color: var(--facis-text-muted); text-transform: uppercase; letter-spacing: 0.04em; }
.rec-metric__value { font-size: 0.82rem; font-weight: 500; color: var(--facis-text); }
.rec-metric__value--impact { color: var(--facis-success); font-weight: 700; }
.confidence-row { display: flex; align-items: center; gap: 0.75rem; }
.confidence-label { font-size: 0.75rem; font-weight: 500; color: var(--facis-text-secondary); min-width: 80px; }
.confidence-bar-bg { flex: 1; height: 6px; background: var(--facis-surface-2); border-radius: 3px; overflow: hidden; }
.confidence-bar-fill { height: 100%; border-radius: 3px; }
.confidence-pct { font-size: 0.8rem; font-weight: 700; color: var(--facis-text); min-width: 36px; text-align: right; }
.advisory-note { display: flex; align-items: center; gap: 0.5rem; font-size: 0.72rem; color: #92400e; background: #fef3c7; padding: 0.4rem 0.625rem; border-radius: var(--facis-radius-sm); }
.advisory-note__icon { font-size: 0.8rem; flex-shrink: 0; }
.table-meta { display: flex; align-items: center; padding: 0.875rem 1.25rem; border-bottom: 1px solid var(--facis-border); }
.table-title { font-size: 0.875rem; font-weight: 600; color: var(--facis-text); }
.impact-text { font-size: 0.8rem; font-weight: 600; color: var(--facis-success); }
.conf-chip { font-size: 0.78rem; font-weight: 700; color: var(--facis-primary); }
.ts { font-size: 0.78rem; color: var(--facis-text-secondary); }
.empty-row { padding: 2rem; text-align: center; color: var(--facis-text-secondary); }
</style>
