apiVersion: v1
kind: Service
metadata:
  name: {{ include "facis-dsp-connector.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "facis-dsp-connector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "facis-dsp-connector.selectorLabels" . | nindent 4 }}
