#!/usr/bin/env python3
"""
Renders services/simulation/orce/flows/facis-simulation-feeds.json from
services/simulation/config/default.yaml.

For each entity declared in default.yaml (and the implicit weather + price
+ visibility), the renderer emits:
    inject-config (function)  →  subflow:<simulator>  →  store-reading (function)
                                                      →  link out feeds.kafka.<topic-tail>

Wiring honours the same dependency ordering as the Python CorrelationEngine:
    weather → pv  (PV reads weather.conditions.{ghi_w_m2,temperature_c})
    city_events → streetlights  (streetlights read active_event)
    everything else fans out from the tick directly.

Run:
    python3 services/simulation/orce/scripts/render-feeds.py
        [--config services/simulation/config/default.yaml]
        [--out    services/simulation/orce/flows/facis-simulation-feeds.json]

Re-runs are deterministic: every node id is sha1(stable-string)[:16], so a
clean diff means nothing changed semantically.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parents[4]  # facis-fap-iot-ai/
DEFAULT_CONFIG = REPO_ROOT / "services/simulation/config/default.yaml"
DEFAULT_OUT = REPO_ROOT / "services/simulation/orce/flows/facis-simulation-feeds.json"
SUBFLOWS_DIR = REPO_ROOT / "services/simulation/orce/subflows"

TAB_ID = "tab-feeds"
TAB_LABEL = "FACIS Simulation — Feeds"
# Fixed id (not nid()-derived) so tick.json's `link-out-tick` can reference it
# in source via its `links` array.
TICK_LINKIN_ID = "linkin-tick-trigger"

# Subflow ids — must match the `id` of each subflow definition. Verified
# against the *.subflow.json files at render time.
SUBFLOW_IDS = {
    "meter": "subflow-facis-meter",
    "pv": "subflow-facis-pv",
    "weather": "subflow-facis-weather",
    "consumer": "subflow-facis-consumer",
    "price": "subflow-facis-price",
    "streetlight": "subflow-facis-streetlights",
    "traffic": "subflow-facis-traffic",
    "visibility": "subflow-facis-visibility",
    "city_events": "subflow-facis-city-events",
}


def nid(*parts: str) -> str:
    """Deterministic Node-RED id: 16 hex chars from sha1(joined parts)."""
    return hashlib.sha1(":".join(parts).encode()).hexdigest()[:16]


def linkin_id_for(link_name: str) -> str:
    """ID of the matching link-in node in facis-simulation-kafka.json.
    Must stay in sync with render-kafka.py."""
    return hashlib.sha1(f"kafka-linkin:{link_name}".encode()).hexdigest()[:16]


def verify_subflow_ids() -> None:
    missing = []
    for kind, sid in SUBFLOW_IDS.items():
        path = SUBFLOWS_DIR / f"{kind.replace('_','-')}-simulator.subflow.json"
        if not path.exists():
            # Some files have different naming
            alt = {
                "meter": "energy-meter-simulator.subflow.json",
                "consumer": "consumer-load-simulator.subflow.json",
                "price": "energy-price-simulator.subflow.json",
                "streetlight": "streetlights-simulator.subflow.json",
                "city_events": "city-events-simulator.subflow.json",
            }.get(kind)
            if alt:
                path = SUBFLOWS_DIR / alt
        if not path.exists():
            missing.append((kind, str(path)))
            continue
        nodes = json.loads(path.read_text())
        actual_id = next((n["id"] for n in nodes if n.get("type") == "subflow"), None)
        if actual_id != sid:
            print(
                f"WARN: subflow id drift for {kind}: expected {sid}, file has {actual_id} ({path.name})",
                file=sys.stderr,
            )
            SUBFLOW_IDS[kind] = actual_id
    if missing:
        for k, p in missing:
            print(f"ERR: subflow file not found for {k}: {p}", file=sys.stderr)
        sys.exit(2)


# ── Node factories ─────────────────────────────────────────────────


def n_tab() -> dict[str, Any]:
    return {
        "id": TAB_ID,
        "type": "tab",
        "label": TAB_LABEL,
        "disabled": False,
        "info": "Auto-generated by services/simulation/orce/scripts/render-feeds.py — do not edit by hand",
    }


def n_link_in(name: str, link: str, wires_to: list[str], y: int, *, id_override: str | None = None) -> dict[str, Any]:
    return {
        "id": id_override or nid("linkin", link),
        "type": "link in",
        "z": TAB_ID,
        "name": name,
        "links": [],
        "x": 90,
        "y": y,
        "wires": [wires_to],
    }


def n_link_out(link: str, x: int, y: int) -> dict[str, Any]:
    return {
        "id": nid("linkout", link),
        "type": "link out",
        "z": TAB_ID,
        "name": f"→ {link}",
        "mode": "link",
        "links": [],
        "x": x,
        "y": y,
        "wires": [],
    }


def n_function(
    fid: str,
    name: str,
    func: str,
    wires_to: list[str],
    x: int,
    y: int,
    initialize: str = "",
) -> dict[str, Any]:
    node = {
        "id": fid,
        "type": "function",
        "z": TAB_ID,
        "name": name,
        "func": func,
        "outputs": 1,
        "timeout": 0,
        "noerr": 0,
        "initialize": initialize,
        "finalize": "",
        "libs": [],
        "x": x,
        "y": y,
        "wires": [wires_to],
    }
    return node


def n_subflow_instance(
    iid: str, kind: str, label: str, wires_to: list[str], x: int, y: int
) -> dict[str, Any]:
    return {
        "id": iid,
        "type": f"subflow:{SUBFLOW_IDS[kind]}",
        "z": TAB_ID,
        "name": label,
        "env": [],
        "x": x,
        "y": y,
        "wires": [wires_to],
    }


# ── Per-entity inject-config emitter ───────────────────────────────


def js_obj(d: dict[str, Any]) -> str:
    """Render a Python dict as a JS object literal (basic)."""
    return json.dumps(d, separators=(",", ":"))


def inject_config_func(entity_kind: str, entity_id: str, config: dict[str, Any]) -> str:
    """
    Emits the function body that copies tick fields into msg.payload and
    attaches the per-entity static config + entity_id.
    """
    return f"""// Auto-rendered: {entity_kind}:{entity_id}
const t = msg.payload || {{}};
msg.payload = {{
    base_seed:    t.base_seed,
    entity_id:    {json.dumps(entity_id)},
    timestamp_ms: t.timestamp_ms,
    timestamp:    t.timestamp,
    site_id:      t.site_id,
    mode:         t.mode,
    config:       {js_obj(config)}
}};
return msg;
"""


def inject_config_with_weather_func(entity_kind: str, entity_id: str, config: dict[str, Any]) -> str:
    """
    Variant for PV: pulls weather from flow context (set by weather-store).
    """
    return f"""// Auto-rendered (with weather): {entity_kind}:{entity_id}
const t = msg.payload || {{}};
const w = global.get('latest_weather');
if (!w) {{
    // weather hasn't fired yet this tick; let pv handle missing weather safely
}}
msg.payload = {{
    base_seed:    t.base_seed,
    entity_id:    {json.dumps(entity_id)},
    timestamp_ms: t.timestamp_ms,
    timestamp:    t.timestamp,
    site_id:      t.site_id,
    mode:         t.mode,
    config:       {js_obj(config)},
    weather:      w || null
}};
return msg;
"""


def inject_streetlight_with_event_func(light_id: str, zone_id: str, config: dict[str, Any]) -> str:
    """
    Streetlight variant: pulls active_event for its zone from flow context.
    """
    return f"""// Auto-rendered streetlight: {light_id} (zone {zone_id})
const t = msg.payload || {{}};
const ev = global.get('active_event_' + {json.dumps(zone_id)}) || null;
msg.payload = {{
    base_seed:    t.base_seed,
    entity_id:    {json.dumps(light_id)},
    timestamp_ms: t.timestamp_ms,
    timestamp:    t.timestamp,
    site_id:      t.site_id,
    city_id:      "city-berlin",
    mode:         t.mode,
    config:       {js_obj(config)},
    active_event: ev
}};
return msg;
"""


# ── Store-reading emitters ─────────────────────────────────────────

STORE_ARRAY_FN = """// Auto-rendered store-by-id (array)
const r = msg.payload;
const id = r["{key}"];
let arr = global.get("{ctx}") || [];
const idx = arr.findIndex((x) => x["{key}"] === id);
if (idx >= 0) arr[idx] = r; else arr.push(r);
global.set("{ctx}", arr);
global.set("last_kafka_tick", new Date().toISOString());
return msg;
"""

STORE_SINGLE_FN = """// Auto-rendered store-single
global.set("{ctx}", msg.payload);
global.set("last_kafka_tick", new Date().toISOString());
return msg;
"""

STORE_EVENT_FN = """// Store active_event so the streetlight branch can read it
global.set('active_event_' + msg.payload.zone_id, msg.payload);
return msg;
"""


# ── Build envelope from incoming tick ──────────────────────────────


def build_envelope_func(site_id: str, total_entities: int) -> str:
    return f"""// Build standard tick envelope; consumed by all per-entity inject-config nodes downstream
const t = msg.payload || {{}};
msg.payload = {{
    base_seed:    Number(env.get('BASE_SEED') || 12345),
    timestamp_ms: t.timestamp_ms || Date.now(),
    timestamp:    t.timestamp    || new Date().toISOString(),
    site_id:      env.get('SITE_ID') || {json.dumps(site_id)},
    mode:         env.get('MODE') || 'normal'
}};
// One-shot: bump engine.registered_entities on first tick
const engine = global.get('engine');
if (engine && engine.registered_entities !== {total_entities}) {{
    engine.registered_entities = {total_entities};
    global.set('engine', engine);
}}
return msg;
"""


# ── Main render ────────────────────────────────────────────────────


def render(config: dict[str, Any]) -> list[dict[str, Any]]:
    nodes: list[dict[str, Any]] = []
    nodes.append(n_tab())

    site_id = config.get("site_id", "site-berlin-001")
    meters = config.get("meters", []) or []
    pv_systems = config.get("pv_systems", []) or []
    consumers = config.get("consumers", []) or []
    sc = config.get("smart_city", {}) or {}
    zones = sc.get("zones", []) or []
    city_id = sc.get("city_id", "city-berlin")
    city_lat = sc.get("latitude", (pv_systems[0].get("latitude", 52.52) if pv_systems else 52.52))
    city_lon = sc.get("longitude", (pv_systems[0].get("longitude", 13.405) if pv_systems else 13.405))

    total_entities = (
        len(meters)
        + len(pv_systems)
        + len(consumers)
        + 1  # weather
        + 1  # price
        + sum(len(z.get("lights", [])) for z in zones)
        + len(zones)  # traffic per zone
        + len(zones)  # city_event per zone
        + 1  # visibility
    )

    # ── Tick entry ─────────────────────────────────────────────────
    build_env_id = nid("fn", "build-envelope")
    fanout_independent_id = nid("fn", "fanout-independent")  # writes to all level-0 + level-1 sources
    nodes.append(
        n_link_in(
            "tick.trigger",
            "tick.trigger",
            [build_env_id],
            y=80,
            id_override=TICK_LINKIN_ID,
        )
    )
    nodes.append(
        n_function(
            build_env_id,
            "build envelope",
            build_envelope_func(site_id, total_entities),
            [fanout_independent_id],
            x=260,
            y=80,
        )
    )

    # The fanout-independent function fires the envelope to every level-0/1 entry
    # by emitting it on a single output and using regular wires (one wire per
    # downstream).  We don't need any code; an identity function with multi-wire
    # is the cleanest path.  Build the wires list as we add downstream nodes.
    fanout_wires: list[str] = []
    fanout_node = n_function(
        fanout_independent_id,
        "fanout to entities",
        "return msg;",
        fanout_wires,
        x=470,
        y=80,
    )
    nodes.append(fanout_node)

    # Helper: append an entity branch ── inject → subflow → store → linkout
    def add_entity_branch(
        kind: str,
        entity_id: str,
        config_obj: dict[str, Any],
        kafka_link: str,
        ctx_key: str | None,
        ctx_mode: str,  # "array" | "single" | "event" | "none"
        x_base: int,
        y: int,
        inject_func_fn=inject_config_func,
        store_id_key: str | None = None,
        link_to_extra: list[str] | None = None,
    ) -> str:
        """
        link_to_extra: extra node ids to wire from store-reading (used for chaining
        streetlight branch off events).  Returns the inject node id (so the caller
        can wire it into fanout_wires).
        """
        inj_id = nid("inj", kind, entity_id)
        sub_id = nid("sub", kind, entity_id)
        store_id = nid("store", kind, entity_id)
        link_id = nid("linkout", kafka_link, kind, entity_id)

        nodes.append(
            n_function(
                inj_id,
                f"cfg:{kind}:{entity_id}",
                inject_func_fn(kind, entity_id, config_obj),
                [sub_id],
                x=x_base,
                y=y,
            )
        )
        nodes.append(
            n_subflow_instance(
                sub_id, kind, f"{kind}:{entity_id}", [store_id], x=x_base + 220, y=y
            )
        )

        store_wires = [link_id]
        if link_to_extra:
            store_wires += link_to_extra

        if ctx_mode == "array":
            assert store_id_key, "array mode needs store_id_key"
            body = STORE_ARRAY_FN.format(ctx=ctx_key, key=store_id_key)
        elif ctx_mode == "single":
            body = STORE_SINGLE_FN.format(ctx=ctx_key)
        elif ctx_mode == "event":
            body = STORE_EVENT_FN
        else:  # none = passthrough
            body = "return msg;"
        nodes.append(
            n_function(
                store_id,
                f"store:{kind}:{entity_id}",
                body,
                store_wires,
                x=x_base + 440,
                y=y,
            )
        )

        nodes.append(
            {
                "id": link_id,
                "type": "link out",
                "z": TAB_ID,
                "name": f"→ {kafka_link}",
                "mode": "link",
                "links": [linkin_id_for(kafka_link)],
                "x": x_base + 660,
                "y": y,
                "wires": [],
            }
        )
        return inj_id

    # ── LEVEL 0: meters / consumers / price (independent) ──────────
    y = 60
    for m in meters:
        cfg = {
            "meter_id": m["id"],
            "base_power_kw": m.get("base_load_kw"),
            "peak_power_kw": m.get("peak_load_kw"),
            "nominal_voltage_v": m.get("nominal_voltage_v"),
            "voltage_variance_pct": m.get("voltage_variance_pct"),
            "nominal_frequency_hz": m.get("nominal_frequency_hz"),
            "frequency_variance_hz": m.get("frequency_variance_hz"),
            "power_factor_min": m.get("power_factor_min"),
            "power_factor_max": m.get("power_factor_max"),
            "initial_energy_kwh": m.get("initial_energy_kwh"),
        }
        y += 60
        inj = add_entity_branch(
            "meter",
            m["id"],
            cfg,
            "feeds.kafka.meter",
            "latest_meters",
            "array",
            x_base=700,
            y=y,
            store_id_key="meter_id",
        )
        fanout_wires.append(inj)

    for c in consumers:
        windows = []
        for w in c.get("operating_windows", []) or []:
            if isinstance(w, dict):
                windows.append({"start_hour": w.get("start_hour"), "end_hour": w.get("end_hour")})
            elif isinstance(w, list) and len(w) == 2:
                windows.append({"start_hour": w[0], "end_hour": w[1]})
        cfg = {
            "device_id": c["id"],
            "device_type": c.get("device_type"),
            "rated_power_kw": c.get("rated_power_kw"),
            "duty_cycle_pct": (c.get("duty_cycle") or 0) * 100,
            "power_variance_pct": c.get("power_variance_pct"),
            "operate_on_weekends": c.get("operate_on_weekends", False),
            "operating_windows": windows,
        }
        y += 60
        inj = add_entity_branch(
            "consumer",
            c["id"],
            cfg,
            "feeds.kafka.consumer",
            "latest_consumers",
            "array",
            x_base=700,
            y=y,
            store_id_key="device_id",
        )
        fanout_wires.append(inj)

    # Energy price (single, hardcoded feed_id)
    price_cfg = {
        "feed_id": "epex-spot-de",
        "night_price": 0.18,
        "morning_peak_price": 0.32,
        "midday_price": 0.24,
        "evening_peak_price": 0.36,
        "evening_price": 0.22,
        "weekend_discount_pct": 10,
        "volatility_pct": 5,
        "min_price": 0.05,
    }
    y += 60
    inj = add_entity_branch(
        "price",
        "epex-spot-de",
        price_cfg,
        "feeds.kafka.price",
        "latest_price",
        "single",
        x_base=700,
        y=y,
    )
    fanout_wires.append(inj)

    # ── LEVEL 1: weather (source for PV) ───────────────────────────
    weather_lat = (pv_systems[0].get("latitude", 52.52) if pv_systems else 52.52)
    weather_lon = (pv_systems[0].get("longitude", 13.405) if pv_systems else 13.405)
    weather_cfg = {
        "latitude": weather_lat,
        "longitude": weather_lon,
        "base_temperature_summer_c": 22.0,
        "base_temperature_winter_c": 2.0,
        "daily_temp_amplitude_c": 8.0,
        "temperature_variance_c": 1.5,
        "base_humidity_percent": 65.0,
        "base_wind_speed_ms": 3.5,
        "prevailing_wind_direction_deg": 270,
        "base_cloud_cover_percent": 40.0,
        "max_clear_sky_ghi_w_m2": 1000.0,
    }
    y += 60
    weather_inject_id = nid("inj", "weather", "weather-001")
    weather_sub_id = nid("sub", "weather", "weather-001")
    weather_store_id = nid("store", "weather", "weather-001")
    weather_link_id = nid("linkout", "feeds.kafka.weather", "weather-001")
    weather_link_city_id = nid("linkout", "feeds.kafka.city.weather", "weather-001")
    pv_fanout_id = nid("fn", "pv-fanout")
    nodes.append(
        n_function(
            weather_inject_id,
            "cfg:weather:weather-001",
            inject_config_func("weather", "weather-001", weather_cfg),
            [weather_sub_id],
            x=700,
            y=y,
        )
    )
    nodes.append(
        n_subflow_instance(
            weather_sub_id,
            "weather",
            "weather:weather-001",
            [weather_store_id],
            x=920,
            y=y,
        )
    )
    nodes.append(
        n_function(
            weather_store_id,
            "store:weather",
            STORE_SINGLE_FN.format(ctx="latest_weather"),
            [weather_link_id, weather_link_city_id, pv_fanout_id],
            x=1140,
            y=y,
        )
    )
    nodes.append(
        {
            "id": weather_link_id,
            "type": "link out",
            "z": TAB_ID,
            "name": "→ feeds.kafka.weather",
            "mode": "link",
            "links": [linkin_id_for("feeds.kafka.weather")],
            "x": 1360,
            "y": y - 20,
            "wires": [],
        }
    )
    nodes.append(
        {
            "id": weather_link_city_id,
            "type": "link out",
            "z": TAB_ID,
            "name": "→ feeds.kafka.city.weather",
            "mode": "link",
            "links": [linkin_id_for("feeds.kafka.city.weather")],
            "x": 1360,
            "y": y + 20,
            "wires": [],
        }
    )
    fanout_wires.append(weather_inject_id)

    # PV fanout: re-emits envelope to every PV inject (now that weather is in flow ctx)
    pv_inject_ids: list[str] = []
    nodes.append(
        n_function(
            pv_fanout_id,
            "pv fanout (after weather)",
            "return msg;",
            pv_inject_ids,  # mutated below
            x=1140,
            y=y + 60,
        )
    )

    for p in pv_systems:
        pv_cfg = {
            "system_id": p["id"],
            "nominal_capacity_kwp": p.get("nominal_capacity_kw"),
            "system_losses_percent": (p.get("losses") or 0) * 100,
            "temperature_coefficient_pct_per_c": (p.get("temperature_coefficient") or 0) * 100,
            "reference_temperature_c": p.get("reference_temperature_c"),
            "noct_c": p.get("noct_c", 45),
            "interval_minutes": 1,
        }
        y += 60
        inj = add_entity_branch(
            "pv",
            p["id"],
            pv_cfg,
            "feeds.kafka.pv",
            "latest_pv",
            "array",
            x_base=1340,
            y=y,
            inject_func_fn=inject_config_with_weather_func,
            store_id_key="system_id",
        )
        pv_inject_ids.append(inj)

    # ── LEVEL 1b: city_events per zone (source for streetlights) ───
    event_fanout_ids: dict[str, str] = {}  # zone_id -> fanout-streetlight node id
    for z in zones:
        zone_id = z["id"]
        ev_inj_id = nid("inj", "city_events", zone_id)
        ev_sub_id = nid("sub", "city_events", zone_id)
        ev_store_id = nid("store", "city_events", zone_id)
        ev_link_id = nid("linkout", "feeds.kafka.event", zone_id)
        sl_fanout_id = nid("fn", "streetlight-fanout", zone_id)
        event_fanout_ids[zone_id] = sl_fanout_id

        ev_cfg = {"zone_id": zone_id}
        y += 60
        nodes.append(
            n_function(
                ev_inj_id,
                f"cfg:city_events:{zone_id}",
                f"""// Auto-rendered city_events: {zone_id}
const t = msg.payload || {{}};
msg.payload = {{
    base_seed:    t.base_seed,
    entity_id:    {json.dumps('events-' + zone_id)},
    timestamp_ms: t.timestamp_ms,
    timestamp:    t.timestamp,
    site_id:      t.site_id,
    city_id:      {json.dumps(city_id)},
    zone_id:      {json.dumps(zone_id)},
    mode:         t.mode,
    config:       {js_obj(ev_cfg)}
}};
return msg;
""",
                [ev_sub_id],
                x=700,
                y=y,
            )
        )
        nodes.append(
            n_subflow_instance(
                ev_sub_id,
                "city_events",
                f"city_events:{zone_id}",
                [ev_store_id],
                x=920,
                y=y,
            )
        )
        nodes.append(
            n_function(
                ev_store_id,
                f"store:city_events:{zone_id}",
                STORE_EVENT_FN,
                [ev_link_id, sl_fanout_id],
                x=1140,
                y=y,
            )
        )
        nodes.append(
            {
                "id": ev_link_id,
                "type": "link out",
                "z": TAB_ID,
                "name": "→ feeds.kafka.event",
                "mode": "link",
                "links": [linkin_id_for("feeds.kafka.event")],
                "x": 1360,
                "y": y,
                "wires": [],
            }
        )
        # streetlight fanout function (will fan out to all lights in this zone)
        nodes.append(
            n_function(
                sl_fanout_id,
                f"streetlight fanout ({zone_id})",
                f"// Fans out to lights in {zone_id}\nreturn msg;",
                [],  # filled below
                x=1140,
                y=y + 30,
            )
        )
        fanout_wires.append(ev_inj_id)

    # ── LEVEL 2: streetlights per zone (depend on event fanout) ────
    for z in zones:
        zone_id = z["id"]
        sl_fanout_node_id = event_fanout_ids[zone_id]
        light_inject_ids: list[str] = []
        for light in z.get("lights", []) or []:
            light_id = light["id"]
            cfg = {
                "light_id": light_id,
                "zone_id": zone_id,
                "rated_power_w": light.get("rated_power_w"),
                "latitude": city_lat,
                "longitude": city_lon,
            }
            y += 60
            inj = add_entity_branch(
                "streetlight",
                light_id,
                cfg,
                "feeds.kafka.light",
                None,  # REST doesn't expose
                "none",
                x_base=1340,
                y=y,
                inject_func_fn=lambda kind, eid, c, _zone=zone_id: inject_streetlight_with_event_func(
                    eid, _zone, c
                ),
            )
            light_inject_ids.append(inj)
        # Wire the streetlight fanout function to all light injects
        for n_obj in nodes:
            if n_obj["id"] == sl_fanout_node_id:
                n_obj["wires"] = [light_inject_ids]
                break

    # ── LEVEL 2b: traffic per zone, visibility per city (independent) ─
    for z in zones:
        zone_id = z["id"]
        cfg = {"zone_id": zone_id, "city_id": city_id}
        y += 60

        # Traffic uses a custom inject (zone_id + city_id at top-level, no config)
        inj_id = nid("inj", "traffic", zone_id)
        sub_id = nid("sub", "traffic", zone_id)
        store_id = nid("store", "traffic", zone_id)
        link_id = nid("linkout", "feeds.kafka.traffic", zone_id)

        nodes.append(
            n_function(
                inj_id,
                f"cfg:traffic:{zone_id}",
                f"""const t = msg.payload || {{}};
msg.payload = {{
    base_seed:    t.base_seed,
    entity_id:    {json.dumps('traffic-' + zone_id)},
    timestamp_ms: t.timestamp_ms,
    timestamp:    t.timestamp,
    site_id:      t.site_id,
    city_id:      {json.dumps(city_id)},
    zone_id:      {json.dumps(zone_id)},
    mode:         t.mode
}};
return msg;
""",
                [sub_id],
                x=700,
                y=y,
            )
        )
        nodes.append(
            n_subflow_instance(sub_id, "traffic", f"traffic:{zone_id}", [store_id], x=920, y=y)
        )
        nodes.append(
            n_function(
                store_id,
                f"store:traffic:{zone_id}",
                "return msg;",
                [link_id],
                x=1140,
                y=y,
            )
        )
        nodes.append(
            {
                "id": link_id,
                "type": "link out",
                "z": TAB_ID,
                "name": "→ feeds.kafka.traffic",
                "mode": "link",
                "links": [linkin_id_for("feeds.kafka.traffic")],
                "x": 1360,
                "y": y,
                "wires": [],
            }
        )
        fanout_wires.append(inj_id)

    # Visibility (city-wide)
    vis_cfg = {"latitude": city_lat, "longitude": city_lon}
    y += 60
    vis_inj_id = nid("inj", "visibility", city_id)
    vis_sub_id = nid("sub", "visibility", city_id)
    vis_store_id = nid("store", "visibility", city_id)
    vis_link_id = nid("linkout", "feeds.kafka.city.weather.visibility", city_id)
    nodes.append(
        n_function(
            vis_inj_id,
            f"cfg:visibility:{city_id}",
            f"""const t = msg.payload || {{}};
msg.payload = {{
    base_seed:    t.base_seed,
    entity_id:    {json.dumps('visibility-' + city_id)},
    timestamp_ms: t.timestamp_ms,
    timestamp:    t.timestamp,
    site_id:      t.site_id,
    city_id:      {json.dumps(city_id)},
    mode:         t.mode,
    config:       {js_obj(vis_cfg)}
}};
return msg;
""",
            [vis_sub_id],
            x=700,
            y=y,
        )
    )
    nodes.append(
        n_subflow_instance(
            vis_sub_id, "visibility", f"visibility:{city_id}", [vis_store_id], x=920, y=y
        )
    )
    nodes.append(
        n_function(
            vis_store_id,
            "store:visibility",
            "return msg;",
            [vis_link_id],
            x=1140,
            y=y,
        )
    )
    nodes.append(
        {
            "id": vis_link_id,
            "type": "link out",
            "z": TAB_ID,
            # Visibility joins sim.smart_city.weather topic
            "name": "→ feeds.kafka.city.weather",
            "mode": "link",
            "links": [linkin_id_for("feeds.kafka.city.weather")],
            "x": 1360,
            "y": y,
            "wires": [],
        }
    )
    fanout_wires.append(vis_inj_id)

    # Now finalize the fanout function's wires to point at all level-0/1 inject nodes
    for n_obj in nodes:
        if n_obj["id"] == fanout_independent_id:
            n_obj["wires"] = [fanout_wires]
            break

    return nodes


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args()

    verify_subflow_ids()
    cfg = yaml.safe_load(args.config.read_text())
    nodes = render(cfg)

    args.out.write_text(json.dumps(nodes, indent=4) + "\n")
    print(f"wrote {args.out} — {len(nodes)} nodes")
    tabs = sum(1 for n in nodes if n.get("type") == "tab")
    instances = sum(1 for n in nodes if str(n.get("type", "")).startswith("subflow:"))
    linkouts = sum(1 for n in nodes if n.get("type") == "link out")
    print(f"  tabs={tabs}  subflow_instances={instances}  link_out={linkouts}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
