apiVersion: v1
kind: Secret
metadata:
  name: {{ include "facis-sftp-ingestion.fullname" . }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "facis-sftp-ingestion.labels" . | nindent 4 }}
type: Opaque
data:
  sftp_password: {{ .Values.sftp.password | b64enc | quote }}
